### ISSUE TITLE
ipp client to printer

### ISSUE THREAD

**Issue by art2crazy** [phin1x/go-ipp#1]
Hi,
I'm quite new to go and just starting with ipp, so please forgive my ignorance. I have a project where one of the goals is to print pdf & text files directly to a printer with some options like tray selection. Printers have ipp build in, so I was hoping to use your library to do that, but it seems that ipp client is geared towards a (local?) cups server - when trying to GetPrinterAttributes, getPrinterUri always returns "localhost/" and "printers/" uri, and getHttpUri will return host:port but again + hardcoded "printers/" + printer name, which for direct connection to the printer will not work, as far as I can tell. I believe it should be "host:port/ipp/print" for both http uri & printer uri. I'm basing my statement on my tests with ippserver from https://github.com/istopwg/ippsample.
So, I guess the question should be, is my assumption that ipp client is not able to connect to printer directly correct, or am I missing something, and if so, could you please point me in the right direction?

Thanks,
art

**Comment by phin1x** [comment]
Hi art,

the library is written and tested as an client for a remote CUPS Server.
I will look into it this week.

**Comment by phin1x** [comment]
Hi @art2crazy 

i don't have a ipp compatible printer, so i can't evaluate your case.
the library works perfect with remote servers (we use the library to manage our cups server). you can craft your own request using the NewRequest and SendRequest function with a uri that is working for you.

greetings,
phin1x
