### ISSUE TITLE
Question: Does golang have project to find the suitable ppd?

### ISSUE THREAD

**Issue by Leadrive** [phin1x/go-ipp#10]
Hi, sorry, I want to ask you a question.

The python project https://github.com/OpenPrinting/system-config-printer
detect printer, find the suitable ppd, and install the printer driver.

Does golang have same project? I want to find the suitable ppd by the printer device-id.
Thank you.

**Comment by phin1x** [comment]
I don't know if such a project exists written in golang.
Maybe you could use the integrated Web UI from CUPS. There you can choose a ppd based on the printer model.
