### ISSUE TITLE
panic: cannot get tag of attribute limit

### ISSUE THREAD

**Issue by Beilusquit90** [phin1x/go-ipp#15]
using post method -> error.
client method -> error...
limits not work =(

**Comment by phin1x** [comment]
Can you provide more information.
Which server is used?
Whats your code?

**Comment by Beilusquit90** [comment]
server caps
`myJobs, err := client.GetJobs(printerName, "", "all", false, taskID, 0, nil)
		if err != nil {
			logrus.Warn("Jironnimooo... ", err)
			return false, err
		}`

if i`m set limit more than 1. they return error

**Comment by phin1x** [comment]
I added the limit attribute to the attribute tag mapping.
