### ISSUE TITLE
Unexpected EOF

### ISSUE THREAD

**Issue by RamonSmit** [phin1x/go-ipp#25]
Hi, 

I'm having a little issue with the sample code thats provided in the readme. 

I'm trying to print a simple PDF document as following:
```go
package main

import (
	"fmt"

	"github.com/phin1x/go-ipp"
)

func main() {
	// create a new ipp client
	client := ipp.NewIPPClient("10.0.2.18", 631, "", "", false)
	// print file
	int, err := client.PrintFile("Invoice.pdf", "lp1", map[string]interface{}{})

	fmt.Println(int, err)
}
```

But for some reason the output of the `Println` ends up with `-1` for the returned integer  and `EOF` for the error. Am I overseeing something? 

Thanks in advance,
Ramon

**Comment by aiminchen** [comment]
Hi
1:Why is there no attribute of sides
for example one-sided  two-sides-short-edge
2:The same request sometimes fails, sometimes succeed and return error code 1024 bad request

**Comment by phin1x** [comment]
the eof errors could come from the printer. the library was mainly build to work with cups server. i never tested the library with printers.
The attributes that are included were the most commonly used attributes in my use case. You can easily add new attributes by adding them to the AttributeTagMapping variable in an init function.

**Comment by RamonSmit** [comment]
Alright, In that case I'll better give up :-). 

Thanks for all the help.
